name: Google Chat
on: 
  pull_request:
    types: [opened, reopened, ready_for_reviewer]
jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-chat@v1
        with:
          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
